export const KAFKA_CONFIG_TOKEN = 'KAFKA_CONFIG_TOKEN';

export const KAFKA_VALUE_META = 'KAFKA_PAYLOAD_META';
export const KAFKA_HEADERS_META = 'KAFKA_HEADERS_META';
export const KAFKA_KEY_META = 'KAFKA_KEY_META';
